//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Synzeal_Qty_Update.Folder
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuotationAndDetailsView
    {
        public string Ref { get; set; }
        public string CompanyName { get; set; }
        public string PONo { get; set; }
        public Nullable<System.DateTime> PODate { get; set; }
        public Nullable<bool> IsImportedQuote { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> MoveToProject { get; set; }
        public string ProductName { get; set; }
        public string Price { get; set; }
        public string CASNo { get; set; }
        public string CATNo { get; set; }
        public string EmailAddress { get; set; }
        public string LeadTime { get; set; }
        public int QuoteDetailsId { get; set; }
        public string ProductRemark { get; set; }
        public int Id { get; set; }
        public string CountryType { get; set; }
        public Nullable<int> ProductId { get; set; }
        public string FollowUpRemark { get; set; }
        public string FollowUpRemarkSecond { get; set; }
        public string FollowupDescription { get; set; }
        public Nullable<bool> IsFollowUpAdminChange { get; set; }
        public Nullable<bool> IsFollowupChange { get; set; }
        public string ContactDetail { get; set; }
        public string FinalPrice { get; set; }
        public bool IsToBe { get; set; }
        public Nullable<bool> IsQuoteApproved { get; set; }
        public Nullable<bool> IsPark { get; set; }
        public Nullable<bool> IsSynthesisLog { get; set; }
        public string UserDistType { get; set; }
        public Nullable<int> AdditionalBatchNo { get; set; }
        public Nullable<int> COAId { get; set; }
        public string QuoteBatchNo { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public bool Auction { get; set; }
        public Nullable<bool> IsRemoveFollowup { get; set; }
        public Nullable<bool> IsFollowupRequired { get; set; }
        public string TrackingNo { get; set; }
        public Nullable<bool> IsOnHold { get; set; }
        public string BatchNo { get; set; }
        public string ActivityStatus { get; set; }
        public string COARefNumber { get; set; }
        public Nullable<bool> IsRFQManually { get; set; }
        public string ClientRef { get; set; }
        public string AddTestCostRemark { get; set; }
        public Nullable<bool> IsConversionReport { get; set; }
        public int Expr1 { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string FollowupStatus { get; set; }
        public string FollowupReason { get; set; }
        public Nullable<decimal> QuoteValue { get; set; }
        public Nullable<bool> FreezeQuote { get; set; }
        public Nullable<bool> IsFollowupInterested { get; set; }
        public Nullable<bool> IsFollowupMail { get; set; }
        public Nullable<bool> IsFollowupCall { get; set; }
        public Nullable<bool> IsFollowupWon { get; set; }
        public Nullable<bool> IsFollowupLost { get; set; }
        public Nullable<bool> IsFollowupMeeting { get; set; }
        public Nullable<bool> IsFollowupLessValue { get; set; }
        public Nullable<bool> IsFollowupNegotiation { get; set; }
        public string FollowupAdminRemark { get; set; }
        public Nullable<bool> Expr2 { get; set; }
        public Nullable<bool> IsFollowupImportant { get; set; }
        public Nullable<decimal> ItemDiscount { get; set; }
    }
}
