//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Synzeal_Qty_Update.Folder
{
    using System;
    using System.Collections.Generic;
    
    public partial class SZ_AdditionalTest
    {
        public int Id { get; set; }
        public string Test { get; set; }
        public Nullable<int> INR { get; set; }
        public Nullable<int> USD { get; set; }
        public Nullable<int> GBP { get; set; }
        public Nullable<int> EURO { get; set; }
    }
}
