//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Synzeal_Qty_Update.Folder
{
    using System;
    using System.Collections.Generic;
    
    public partial class SZ_PRRequest
    {
        public int Id { get; set; }
        public string Ref { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string RaisedBy { get; set; }
        public int RaisedByUserId { get; set; }
        public int Labno { get; set; }
        public int SubscientistId { get; set; }
        public string SubscientistName { get; set; }
        public string EmployeeCode { get; set; }
        public int ProductId { get; set; }
        public string APIName { get; set; }
        public Nullable<int> APIID { get; set; }
        public string CATNo { get; set; }
        public string CASNo { get; set; }
        public string ProductName { get; set; }
        public string Density { get; set; }
        public string MolFormula { get; set; }
        public string MolWeight { get; set; }
        public int TotalQty { get; set; }
        public int PackSize { get; set; }
        public int NoofPack { get; set; }
        public string UoM { get; set; }
        public string Make { get; set; }
        public string SupplierRef { get; set; }
        public int Status { get; set; }
        public string ReceivedQuotation { get; set; }
        public Nullable<bool> IsRequestClosed { get; set; }
        public string ClosedBy { get; set; }
        public Nullable<System.DateTime> ClosedDate { get; set; }
    }
}
