//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Synzeal_Qty_Update.Folder
{
    using System;
    using System.Collections.Generic;
    
    public partial class SZ_Popup
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string FilePath { get; set; }
        public bool IsGeneral { get; set; }
        public bool IsEmailOrGroup { get; set; }
        public Nullable<int> SZPopupGroupId { get; set; }
        public bool IsActive { get; set; }
        public bool IsSystemPopup { get; set; }
    
        public virtual SZ_PopupGroup SZ_PopupGroup { get; set; }
    }
}
