//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Synzeal_Qty_Update.Folder
{
    using System;
    using System.Collections.Generic;
    
    public partial class SZ_QuoteDetailsComment
    {
        public int Id { get; set; }
        public int QuotationDetailsId { get; set; }
        public string ApprovedComment { get; set; }
        public int GeneratedUserid { get; set; }
        public string GeneratedUserName { get; set; }
        public bool IsQcView { get; set; }
        public bool IsScientistView { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual SZ_QuotationDetail SZ_QuotationDetail { get; set; }
    }
}
