//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Synzeal_Qty_Update.Folder
{
    using System;
    using System.Collections.Generic;
    
    public partial class SZ_Quotation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SZ_Quotation()
        {
            this.SZ_QuotationDetail = new HashSet<SZ_QuotationDetail>();
            this.SZ_QuotationPDF = new HashSet<SZ_QuotationPDF>();
        }
    
        public int Id { get; set; }
        public string CompanyName { get; set; }
        public string EmailAddress { get; set; }
        public bool IsImageAttach { get; set; }
        public string PONo { get; set; }
        public string Remark { get; set; }
        public Nullable<int> TermsId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Ref { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<System.DateTime> PODate { get; set; }
        public Nullable<bool> IsImportedQuote { get; set; }
        public string CountryType { get; set; }
        public Nullable<bool> IsToBe { get; set; }
        public string ClientRef { get; set; }
        public string Attachment { get; set; }
        public string SuggChemName { get; set; }
        public Nullable<bool> IsPayment { get; set; }
        public Nullable<bool> Auction { get; set; }
        public string EmailCC { get; set; }
        public Nullable<bool> IsQuoteApproved { get; set; }
        public string UserDistType { get; set; }
        public Nullable<bool> IsRemoveFollowup { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<bool> IsPark { get; set; }
        public Nullable<bool> IsCOA { get; set; }
        public string QuoteTotal { get; set; }
        public string FollowUpComment { get; set; }
        public Nullable<bool> IsFollowupRequired { get; set; }
        public string ApprovedBy { get; set; }
        public string ParkReason { get; set; }
        public Nullable<bool> IsInstock { get; set; }
        public Nullable<bool> IsCustomSynthesis { get; set; }
        public string LayoutType { get; set; }
        public Nullable<bool> IsPreviewed { get; set; }
        public Nullable<bool> IsReviewed { get; set; }
        public string QuoteComment { get; set; }
        public Nullable<bool> IsWorking { get; set; }
        public Nullable<System.DateTime> WorkingDate { get; set; }
        public string WorkingUserName { get; set; }
        public string PaymentTerm { get; set; }
        public Nullable<bool> IsShippedCharge { get; set; }
        public Nullable<bool> IsShowDashboard { get; set; }
        public string PurchaseName { get; set; }
        public string PurchaseContactNo { get; set; }
        public string PurchaseEmail { get; set; }
        public string PurchaseAddress { get; set; }
        public string PurchaseCity { get; set; }
        public string PurchaseCountry { get; set; }
        public string TechnicalName { get; set; }
        public string TechnicalContactNo { get; set; }
        public string TechnicalEmail { get; set; }
        public string TechnicalAddress { get; set; }
        public string TechnicalCity { get; set; }
        public string TechnicalCountry { get; set; }
        public string Currency { get; set; }
        public Nullable<bool> IsAnalyticalData { get; set; }
        public Nullable<bool> IsRegret { get; set; }
        public string QuotePDF { get; set; }
        public Nullable<System.DateTime> EmailReceivedDate { get; set; }
        public Nullable<bool> IsCompleted { get; set; }
        public Nullable<System.DateTime> QuoteCompDate { get; set; }
        public Nullable<bool> IsSampleQuote { get; set; }
        public Nullable<bool> HideButton { get; set; }
        public Nullable<bool> IsReminder { get; set; }
        public Nullable<bool> IsStudy { get; set; }
        public Nullable<bool> IsRFQ { get; set; }
        public Nullable<bool> IsRFQManually { get; set; }
        public Nullable<bool> IsPreApproved { get; set; }
        public Nullable<bool> IsRevision { get; set; }
        public Nullable<int> QuoteValidDay { get; set; }
        public Nullable<int> AssignTo { get; set; }
        public Nullable<bool> IsUnderCorrection { get; set; }
        public Nullable<int> HelpScoatNumber { get; set; }
        public Nullable<int> DocumentTypeId { get; set; }
        public Nullable<bool> IsCustomPDFLayout { get; set; }
        public string Url { get; set; }
        public string ConversionNumber { get; set; }
        public string IncoTerm { get; set; }
        public string POUrl { get; set; }
        public string ExternalComment { get; set; }
        public string FollowupStatus { get; set; }
        public string FollowupReason { get; set; }
        public Nullable<decimal> QuoteValue { get; set; }
        public Nullable<decimal> POValue { get; set; }
        public Nullable<bool> FreezeQuote { get; set; }
        public Nullable<bool> IsFollowupInterested { get; set; }
        public Nullable<bool> IsFollowupMail { get; set; }
        public Nullable<bool> IsFollowupCall { get; set; }
        public Nullable<bool> IsFollowupWon { get; set; }
        public Nullable<bool> IsFollowupLost { get; set; }
        public string FollowupAdminRemark { get; set; }
        public Nullable<bool> IsFollowupMeeting { get; set; }
        public Nullable<bool> IsFollowupLessValue { get; set; }
        public Nullable<bool> IsFollowupNegotiation { get; set; }
        public Nullable<bool> IsFollowupImportant { get; set; }
        public Nullable<int> CountryTypeId { get; set; }
        public Nullable<decimal> ShippingCharges { get; set; }
    
        public virtual SZ_CompanyList SZ_CompanyList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SZ_QuotationDetail> SZ_QuotationDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SZ_QuotationPDF> SZ_QuotationPDF { get; set; }
    }
}
