//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Synzeal_Qty_Update.Folder
{
    using System;
    using System.Collections.Generic;
    
    public partial class SZ_Survey
    {
        public int Id { get; set; }
        public string Question1 { get; set; }
        public string Question2 { get; set; }
        public string Question3 { get; set; }
        public string Question4 { get; set; }
        public string Question5 { get; set; }
        public string Question6 { get; set; }
        public string Question7 { get; set; }
        public string Question8 { get; set; }
        public string Question9 { get; set; }
        public string Question10 { get; set; }
        public string Question11 { get; set; }
        public string Question12 { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Telephone { get; set; }
        public string Country { get; set; }
        public Nullable<System.DateTime> Createddate { get; set; }
        public string Question1Message { get; set; }
        public string Question2Message { get; set; }
        public string Question3Message { get; set; }
        public string Question4Message { get; set; }
        public string Question5Message { get; set; }
        public string Question6Message { get; set; }
        public string Question7Message { get; set; }
        public string Question8Message { get; set; }
        public string Question9Message { get; set; }
        public string Question10Message { get; set; }
        public Nullable<bool> IsNewsLetter { get; set; }
        public string Company { get; set; }
        public string Designation { get; set; }
        public string Question13 { get; set; }
        public string Question14 { get; set; }
        public string Question15 { get; set; }
        public string Question16 { get; set; }
        public string Question17 { get; set; }
        public string Question11Message { get; set; }
        public string Question12Message { get; set; }
        public string Question13Message { get; set; }
        public string Question14Message { get; set; }
        public string Question15Message { get; set; }
        public string Question16Message { get; set; }
    }
}
