//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Synzeal_Qty_Update.Folder
{
    using System;
    using System.Collections.Generic;
    
    public partial class SZ_UserDashboard
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public string UserName { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> AllDetails { get; set; }
        public Nullable<int> WithoutCatNo { get; set; }
        public Nullable<int> WithoutCasNo { get; set; }
        public Nullable<int> WithoutPrice { get; set; }
        public Nullable<int> TotalAdded { get; set; }
        public Nullable<int> CatNoRevision { get; set; }
        public Nullable<int> CASNoRevision { get; set; }
        public Nullable<int> PriceRevision { get; set; }
        public Nullable<int> TotalRevisionProduct { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    }
}
