//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Synzeal_AutoBackup.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SZ_EmailSuggestion
    {
        public int Id { get; set; }
        public int CompanyID { get; set; }
        public string ToAddress { get; set; }
        public string CCAddress { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual SZ_CompanyList SZ_CompanyList { get; set; }
    }
}
