//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Synzeal_AutoBackup.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SZ_NameMaster
    {
        public int Id { get; set; }
        public string Sku { get; set; }
        public string EP { get; set; }
        public string USP { get; set; }
        public string ChemDraw { get; set; }
        public string Other { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string EPChemicalName { get; set; }
        public string USPChemicalName { get; set; }
        public string OtherNameOne { get; set; }
        public string OtherNameSecond { get; set; }
        public string OtherNameThird { get; set; }
        public string OtherNameFour { get; set; }
        public string OtherNameFive { get; set; }
        public string OtherNameSix { get; set; }
        public string OtherNameSeven { get; set; }
    }
}
