//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Synzeal_AutoBackup.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SZ_PriceList
    {
        public int Id { get; set; }
        public Nullable<int> ProductId { get; set; }
        public string TenPrice { get; set; }
        public string TwentyFivePrice { get; set; }
        public string FiftyPrice { get; set; }
        public string HundredPrice { get; set; }
        public string TwoHundredPrice { get; set; }
        public string Discount { get; set; }
        public string LeadTime { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
