//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Synzeal_AutoBackup.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SZ_QuotationDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SZ_QuotationDetail()
        {
            this.SZ_ClubQuote = new HashSet<SZ_ClubQuote>();
            this.SZ_QuoteDetailForm = new HashSet<SZ_QuoteDetailForm>();
        }
    
        public int Id { get; set; }
        public int QuoteId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public string ProductName { get; set; }
        public string CASNo { get; set; }
        public string ImagePath { get; set; }
        public string Price { get; set; }
        public string LeadTime { get; set; }
        public bool IsUploadServer { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CATNo { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public string ProjectType { get; set; }
        public Nullable<int> ScientistCustomerId { get; set; }
        public string RequiredQty { get; set; }
        public Nullable<int> ProjectStatus { get; set; }
        public Nullable<int> ScientistStatus { get; set; }
        public string BatchCode1 { get; set; }
        public string Qty1 { get; set; }
        public string BatchCode2 { get; set; }
        public string Qty2 { get; set; }
        public string Courier { get; set; }
        public string TrackingNo { get; set; }
        public string Location { get; set; }
        public string RefName { get; set; }
        public string PurposeDispatch { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<int> DispatchedStatus { get; set; }
        public Nullable<int> ProcessState { get; set; }
        public Nullable<System.DateTime> PackDate { get; set; }
        public string DeliveryStatus { get; set; }
        public string DataPending { get; set; }
        public Nullable<System.DateTime> TrackingNoDate { get; set; }
        public Nullable<System.DateTime> EstimateCompleteDate { get; set; }
        public Nullable<bool> MoveToProject { get; set; }
        public Nullable<bool> MoveToDispatch { get; set; }
        public string BatchNo { get; set; }
        public Nullable<int> AdditionalBatchNo { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> MoveToInvoice { get; set; }
        public string AdminScientistStatus { get; set; }
        public Nullable<int> SrPo { get; set; }
        public string InvoiceRemark { get; set; }
        public string InvoiceNo { get; set; }
        public string PaymentStatus { get; set; }
        public Nullable<bool> IsOnHold { get; set; }
        public Nullable<System.DateTime> MoveProjectDate { get; set; }
        public Nullable<System.DateTime> MoveDispatchDate { get; set; }
        public Nullable<System.DateTime> MoveToInvoiceDate { get; set; }
        public Nullable<System.DateTime> MoveToScientistDate { get; set; }
        public string ProductRemark { get; set; }
        public Nullable<bool> IsDataApproved { get; set; }
        public string ScientistRemark { get; set; }
        public string DataApprovedStatus { get; set; }
        public Nullable<System.DateTime> DataApprovalDate { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public string PurchaseStatus { get; set; }
        public Nullable<System.DateTime> Instockdate { get; set; }
        public string LastStatus { get; set; }
        public string COAPath { get; set; }
        public string AnalyticalData { get; set; }
        public string ClientRemark { get; set; }
        public string ClientAddress { get; set; }
        public string AttachedDataList { get; set; }
        public string ClientStatus { get; set; }
        public string SubScientistName { get; set; }
        public string FollowUpRemark { get; set; }
        public string FollowUpRemarkSecond { get; set; }
        public Nullable<bool> IsPayment { get; set; }
        public Nullable<bool> IsDispatchApprove { get; set; }
        public Nullable<System.DateTime> EstimateDispatchDate { get; set; }
        public string OrderRemark { get; set; }
        public Nullable<System.DateTime> LastUploadDate { get; set; }
        public string Reason { get; set; }
        public Nullable<System.DateTime> ResponseClientRemarkDate { get; set; }
        public Nullable<bool> IsFirstTimeDataUpload { get; set; }
        public string QueryText { get; set; }
        public Nullable<System.DateTime> QueryDate { get; set; }
        public Nullable<bool> IsSynthesisLog { get; set; }
        public Nullable<bool> IsAssignScientistQuery { get; set; }
        public Nullable<bool> IsAssignProjectQuery { get; set; }
        public string Explanation { get; set; }
        public Nullable<System.DateTime> ReportInvoiceDate { get; set; }
        public Nullable<System.DateTime> COAApprovedDate { get; set; }
        public Nullable<bool> IsQueryResolved { get; set; }
        public Nullable<System.DateTime> QueryResolvedDate { get; set; }
        public Nullable<bool> IsDispatchedLock { get; set; }
        public Nullable<bool> IsFollowUpAdminChange { get; set; }
        public Nullable<bool> IsFollowupChange { get; set; }
        public string FollowupDescription { get; set; }
        public string ContactDetail { get; set; }
        public string DifficultyLevel { get; set; }
        public Nullable<bool> IsPriority { get; set; }
        public Nullable<bool> IsPark { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SZ_ClubQuote> SZ_ClubQuote { get; set; }
        public virtual SZ_Quotation SZ_Quotation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SZ_QuoteDetailForm> SZ_QuoteDetailForm { get; set; }
    }
}
