//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Synzeal_AutoBackup.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SZ_TempQuotationDetail
    {
        public int Id { get; set; }
        public int QuoteId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public string ProductName { get; set; }
        public string CASNo { get; set; }
        public string ImagePath { get; set; }
        public string Price { get; set; }
        public string LeadTime { get; set; }
        public bool IsUploadServer { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.Guid UniqueId { get; set; }
        public string CATNo { get; set; }
        public string BackNoDetail { get; set; }
        public Nullable<int> ClubQuoteId { get; set; }
        public string ProductRemark { get; set; }
        public Nullable<System.DateTime> EstimateDispatchDate { get; set; }
        public Nullable<bool> IsSynthesisLog { get; set; }
    }
}
