//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Synzeal_Export_Catalogue.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerRole
    {
        public CustomerRole()
        {
            this.AclRecords = new HashSet<AclRecord>();
            this.TierPrices = new HashSet<TierPrice>();
            this.Customers = new HashSet<Customer>();
            this.PermissionRecords = new HashSet<PermissionRecord>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public bool FreeShipping { get; set; }
        public bool TaxExempt { get; set; }
        public bool Active { get; set; }
        public bool IsSystemRole { get; set; }
        public string SystemName { get; set; }
        public int PurchasedWithProductId { get; set; }
    
        public virtual ICollection<AclRecord> AclRecords { get; set; }
        public virtual ICollection<TierPrice> TierPrices { get; set; }
        public virtual ICollection<Customer> Customers { get; set; }
        public virtual ICollection<PermissionRecord> PermissionRecords { get; set; }
    }
}
