//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Synzeal_Export_Catalogue.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SZ_InventoryLog
    {
        public int Id { get; set; }
        public int InventoryId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string PreviousQty { get; set; }
        public string CurrentQty { get; set; }
        public string Reason { get; set; }
        public Nullable<int> UserId { get; set; }
        public string PoNumber { get; set; }
        public string UserName { get; set; }
    }
}
