//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Synzeal_Export_Catalogue.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SZ_Notification
    {
        public int Id { get; set; }
        public int CompanyId { get; set; }
        public string Message { get; set; }
        public bool IsRead { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
