//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Synzeal_Export_Catalogue.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SZ_Project
    {
        public SZ_Project()
        {
            this.SZ_ProjectDetail = new HashSet<SZ_ProjectDetail>();
        }
    
        public int Id { get; set; }
        public string PONo { get; set; }
        public Nullable<System.DateTime> PODate { get; set; }
        public string Company { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Revised1 { get; set; }
        public string Revised2 { get; set; }
        public string Revised3 { get; set; }
        public Nullable<System.DateTime> ActualDispatch { get; set; }
    
        public virtual ICollection<SZ_ProjectDetail> SZ_ProjectDetail { get; set; }
    }
}
