//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Synzeal_Export_Catalogue.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SZ_PopupGroup
    {
        public SZ_PopupGroup()
        {
            this.SZ_Popup = new HashSet<SZ_Popup>();
            this.SZ_PopupGroupEmailList = new HashSet<SZ_PopupGroupEmailList>();
        }
    
        public int Id { get; set; }
        public string GroupName { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual ICollection<SZ_Popup> SZ_Popup { get; set; }
        public virtual ICollection<SZ_PopupGroupEmailList> SZ_PopupGroupEmailList { get; set; }
    }
}
