//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Synzeal_Export_Catalogue.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SZ_QuoteSummary
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string Username { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string UpdatedUsername { get; set; }
        public int Clarification { get; set; }
        public int Upload { get; set; }
        public int Complex { get; set; }
        public int Regretted { get; set; }
    }
}
