//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Synzeal_Export_Catalogue.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SZ_SampleRequest
    {
        public SZ_SampleRequest()
        {
            this.SZ_SampleRequestDetail = new HashSet<SZ_SampleRequestDetail>();
        }
    
        public int Id { get; set; }
        public string RequestNo { get; set; }
        public string Name { get; set; }
        public System.DateTime RequestDate { get; set; }
        public string Department { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<bool> IsConfirm { get; set; }
        public Nullable<int> CreateduserId { get; set; }
    
        public virtual ICollection<SZ_SampleRequestDetail> SZ_SampleRequestDetail { get; set; }
    }
}
