//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Synzeal_Export_Catalogue.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SZ_TempQuickAdd
    {
        public int Id { get; set; }
        public int ProductId { get; set; }
        public string CasNo { get; set; }
        public string CatNo { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> ScientistId { get; set; }
        public string Qty { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
