//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Synzeal_Inventory.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatMessage
    {
        public int ChatMessageID { get; set; }
        public int FromUserID { get; set; }
        public int ToUserID { get; set; }
        public string Message { get; set; }
        public string Status { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public System.DateTime ViewedOn { get; set; }
        public bool IsActive { get; set; }
    }
}
