//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Synzeal_Inventory.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int Id { get; set; }
        public int SentUserId { get; set; }
        public string SentUserName { get; set; }
        public int RecivedUserId { get; set; }
        public string RecivedUserName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Message { get; set; }
        public int Type { get; set; }
    }
}
