//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Synzeal_Inventory.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SZ_CategoryMasterRange
    {
        public int Id { get; set; }
        public Nullable<int> TenStartRange { get; set; }
        public Nullable<int> TenEndRange { get; set; }
        public Nullable<int> TwentyfiveStartRange { get; set; }
        public Nullable<int> TwentyfiveEndRange { get; set; }
        public Nullable<int> FiftyStartRange { get; set; }
        public Nullable<int> FiftyEndRange { get; set; }
        public Nullable<int> OnehundredStartRange { get; set; }
        public Nullable<int> OnehundredEndRange { get; set; }
        public Nullable<int> TwohundredFiftyStartRange { get; set; }
        public Nullable<int> TwohundredFiftyEndRange { get; set; }
        public Nullable<int> FivehundredStartRange { get; set; }
        public Nullable<int> FivehundredEndRange { get; set; }
        public Nullable<int> OneThousandStartRange { get; set; }
        public Nullable<int> OneThousandEndRange { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
    }
}
