//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Synzeal_Inventory.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SZ_RuleDetail
    {
        public int Id { get; set; }
        public int RuleId { get; set; }
        public int Condition { get; set; }
        public string Tag { get; set; }
        public int Type { get; set; }
        public int Query { get; set; }
        public string Value { get; set; }
    
        public virtual SZ_Rule SZ_Rule { get; set; }
    }
}
