//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Synzeal_Inventory.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SZ_ReservedQty
    {
        public int Id { get; set; }
        public int ProductId { get; set; }
        public string CATNo { get; set; }
        public int BatchId { get; set; }
        public string BatchNo { get; set; }
        public int CreatedBy { get; set; }
        public string CreatedByName { get; set; }
        public int Qty { get; set; }
        public string Reason { get; set; }
        public string Ref { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual SZ_Inventory SZ_Inventory { get; set; }
    }
}
