//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Synzeal_SAP_Stock_API.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SZ_CompanyAddress
    {
        public int Id { get; set; }
        public int CompanyId { get; set; }
        public string Address { get; set; }
        public string Country { get; set; }
        public string Pincode { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Createdby { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public string TelNo { get; set; }
        public bool IsBillAddress { get; set; }
    
        public virtual SZ_CompanyList SZ_CompanyList { get; set; }
    }
}
