//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Synzeal_SAP_Stock_API.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SZ_Clientremark
    {
        public int Id { get; set; }
        public int QuoteDetailsId { get; set; }
        public string ClientRemarks { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int SentUserId { get; set; }
        public string SentUserName { get; set; }
        public string Attachment { get; set; }
    
        public virtual SZ_QuotationDetail SZ_QuotationDetail { get; set; }
    }
}
