//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Synzeal_SAP_Stock_API.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SZ_Invoice
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> DispatchDate { get; set; }
        public string BasicValue { get; set; }
        public string InvoiceNo { get; set; }
        public string PaymentTerm { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string Courier { get; set; }
        public string TrackingNo { get; set; }
        public string DispatchDetail { get; set; }
        public string DeliveryConfirmation { get; set; }
        public string PaymentFollowUp { get; set; }
        public string PaymentDetail { get; set; }
        public string CForm { get; set; }
        public string FirstEMail { get; set; }
        public string SecondEmail { get; set; }
        public string ContactNo { get; set; }
        public string PaymentStatus { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<int> ProjectDetailsId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
