//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Synzeal_SAP_Stock_API.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SZ_PerformaInvoice
    {
        public int Id { get; set; }
        public int CompanyId { get; set; }
        public string CustomerPoNo { get; set; }
        public string BillCompanyName { get; set; }
        public string ShipCompanyName { get; set; }
        public string PerformaInvoiceNo { get; set; }
        public System.DateTime PerformaInvoiceDate { get; set; }
        public string TrackingNo { get; set; }
        public string Courier { get; set; }
        public string TermsId { get; set; }
        public int BillAddressId { get; set; }
        public string BillCountry { get; set; }
        public int ShipAddressId { get; set; }
        public string ShipCountry { get; set; }
        public string BillTelno { get; set; }
        public string ShipTelno { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public int ShippingCost { get; set; }
        public string Temperature { get; set; }
        public string GrossWeight { get; set; }
        public string NetWeight { get; set; }
        public string HSNCode { get; set; }
        public string Currency { get; set; }
        public string Incoterm { get; set; }
        public string PortOfDischarge { get; set; }
        public Nullable<bool> IsVisibleGood { get; set; }
        public string BillGSTNo { get; set; }
        public string ShipGSTNo { get; set; }
        public Nullable<bool> IsIGST { get; set; }
    }
}
