//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Synzeal_SAP_Stock_API.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SZ_QuotationDetailLog
    {
        public int Id { get; set; }
        public int QuoteId { get; set; }
        public int QuoteDetailsId { get; set; }
        public string QuoteRef { get; set; }
        public System.DateTime Datetime { get; set; }
        public string PropertyName { get; set; }
        public string FieldName { get; set; }
        public string Before { get; set; }
        public string After { get; set; }
        public int UserId { get; set; }
        public string Username { get; set; }
    }
}
