//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Synzeal_SAP_Stock_API.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SZ_SolutionModule
    {
        public int Id { get; set; }
        public Nullable<int> SolutionNumber { get; set; }
        public string Status { get; set; }
        public string Solution { get; set; }
        public string Symptom { get; set; }
        public string Cause { get; set; }
        public string Remark { get; set; }
        public string Attachment { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string ProductName { get; set; }
        public string CASNo { get; set; }
        public string CATNo { get; set; }
        public string BatchNo { get; set; }
    }
}
