//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Synzeal_BatchFormData_Sync.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SynzealEntities : DbContext
    {
        public SynzealEntities()
            : base("name=SynzealEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AclRecord> AclRecords { get; set; }
        public virtual DbSet<ActivityLog> ActivityLogs { get; set; }
        public virtual DbSet<ActivityLogType> ActivityLogTypes { get; set; }
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<AddressAttribute> AddressAttributes { get; set; }
        public virtual DbSet<AddressAttributeValue> AddressAttributeValues { get; set; }
        public virtual DbSet<Affiliate> Affiliates { get; set; }
        public virtual DbSet<BackInStockSubscription> BackInStockSubscriptions { get; set; }
        public virtual DbSet<BlogComment> BlogComments { get; set; }
        public virtual DbSet<BlogPost> BlogPosts { get; set; }
        public virtual DbSet<Campaign> Campaigns { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<CategoryTemplate> CategoryTemplates { get; set; }
        public virtual DbSet<CheckoutAttribute> CheckoutAttributes { get; set; }
        public virtual DbSet<CheckoutAttributeValue> CheckoutAttributeValues { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Country1> Countries1 { get; set; }
        public virtual DbSet<CrossSellProduct> CrossSellProducts { get; set; }
        public virtual DbSet<Currency> Currencies { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<CustomerAttribute> CustomerAttributes { get; set; }
        public virtual DbSet<CustomerAttributeValue> CustomerAttributeValues { get; set; }
        public virtual DbSet<CustomerRole> CustomerRoles { get; set; }
        public virtual DbSet<DeliveryDate> DeliveryDates { get; set; }
        public virtual DbSet<Discount> Discounts { get; set; }
        public virtual DbSet<DiscountRequirement> DiscountRequirements { get; set; }
        public virtual DbSet<DiscountUsageHistory> DiscountUsageHistories { get; set; }
        public virtual DbSet<Download> Downloads { get; set; }
        public virtual DbSet<EmailAccount> EmailAccounts { get; set; }
        public virtual DbSet<ExternalAuthenticationRecord> ExternalAuthenticationRecords { get; set; }
        public virtual DbSet<Forums_Forum> Forums_Forum { get; set; }
        public virtual DbSet<Forums_Group> Forums_Group { get; set; }
        public virtual DbSet<Forums_Post> Forums_Post { get; set; }
        public virtual DbSet<Forums_PrivateMessage> Forums_PrivateMessage { get; set; }
        public virtual DbSet<Forums_Subscription> Forums_Subscription { get; set; }
        public virtual DbSet<Forums_Topic> Forums_Topic { get; set; }
        public virtual DbSet<GenericAttribute> GenericAttributes { get; set; }
        public virtual DbSet<GiftCard> GiftCards { get; set; }
        public virtual DbSet<GiftCardUsageHistory> GiftCardUsageHistories { get; set; }
        public virtual DbSet<GoogleProduct> GoogleProducts { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<Group_Newsletter_Map> Group_Newsletter_Map { get; set; }
        public virtual DbSet<Language> Languages { get; set; }
        public virtual DbSet<LocaleStringResource> LocaleStringResources { get; set; }
        public virtual DbSet<LocalizedProperty> LocalizedProperties { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
        public virtual DbSet<Manufacturer> Manufacturers { get; set; }
        public virtual DbSet<ManufacturerTemplate> ManufacturerTemplates { get; set; }
        public virtual DbSet<MeasureDimension> MeasureDimensions { get; set; }
        public virtual DbSet<MeasureWeight> MeasureWeights { get; set; }
        public virtual DbSet<MessageTemplate> MessageTemplates { get; set; }
        public virtual DbSet<MessageTemplateNewsLetter> MessageTemplateNewsLetters { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<NewsComment> NewsComments { get; set; }
        public virtual DbSet<Newsletter> Newsletters { get; set; }
        public virtual DbSet<NewsLetterSubscription> NewsLetterSubscriptions { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<OrderItem> OrderItems { get; set; }
        public virtual DbSet<OrderNote> OrderNotes { get; set; }
        public virtual DbSet<PaymentTerm> PaymentTerms { get; set; }
        public virtual DbSet<PermissionRecord> PermissionRecords { get; set; }
        public virtual DbSet<Picture> Pictures { get; set; }
        public virtual DbSet<Poll> Polls { get; set; }
        public virtual DbSet<PollAnswer> PollAnswers { get; set; }
        public virtual DbSet<PollVotingRecord> PollVotingRecords { get; set; }
        public virtual DbSet<PredefinedProductAttributeValue> PredefinedProductAttributeValues { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Product_Category_Mapping> Product_Category_Mapping { get; set; }
        public virtual DbSet<Product_Manufacturer_Mapping> Product_Manufacturer_Mapping { get; set; }
        public virtual DbSet<Product_Picture_Mapping> Product_Picture_Mapping { get; set; }
        public virtual DbSet<Product_ProductAttribute_Mapping> Product_ProductAttribute_Mapping { get; set; }
        public virtual DbSet<Product_SpecificationAttribute_Mapping> Product_SpecificationAttribute_Mapping { get; set; }
        public virtual DbSet<ProductAttribute> ProductAttributes { get; set; }
        public virtual DbSet<ProductAttributeCombination> ProductAttributeCombinations { get; set; }
        public virtual DbSet<ProductAttributeValue> ProductAttributeValues { get; set; }
        public virtual DbSet<ProductReview> ProductReviews { get; set; }
        public virtual DbSet<ProductReviewHelpfulness> ProductReviewHelpfulnesses { get; set; }
        public virtual DbSet<ProductTag> ProductTags { get; set; }
        public virtual DbSet<ProductTemplate> ProductTemplates { get; set; }
        public virtual DbSet<ProductWarehouseInventory> ProductWarehouseInventories { get; set; }
        public virtual DbSet<QueuedEmail> QueuedEmails { get; set; }
        public virtual DbSet<RecurringPayment> RecurringPayments { get; set; }
        public virtual DbSet<RecurringPaymentHistory> RecurringPaymentHistories { get; set; }
        public virtual DbSet<RelatedProduct> RelatedProducts { get; set; }
        public virtual DbSet<ReturnRequest> ReturnRequests { get; set; }
        public virtual DbSet<RewardPointsHistory> RewardPointsHistories { get; set; }
        public virtual DbSet<Rfq> Rfqs { get; set; }
        public virtual DbSet<ScheduleTask> ScheduleTasks { get; set; }
        public virtual DbSet<SearchTerm> SearchTerms { get; set; }
        public virtual DbSet<Setting> Settings { get; set; }
        public virtual DbSet<Shipment> Shipments { get; set; }
        public virtual DbSet<ShipmentItem> ShipmentItems { get; set; }
        public virtual DbSet<ShippingByWeight> ShippingByWeights { get; set; }
        public virtual DbSet<ShippingMethod> ShippingMethods { get; set; }
        public virtual DbSet<ShoppingCartItem> ShoppingCartItems { get; set; }
        public virtual DbSet<SpecificationAttribute> SpecificationAttributes { get; set; }
        public virtual DbSet<SpecificationAttributeOption> SpecificationAttributeOptions { get; set; }
        public virtual DbSet<StateProvince> StateProvinces { get; set; }
        public virtual DbSet<Store> Stores { get; set; }
        public virtual DbSet<StoreMapping> StoreMappings { get; set; }
        public virtual DbSet<SystemLog> SystemLogs { get; set; }
        public virtual DbSet<SZ_CartRfq> SZ_CartRfq { get; set; }
        public virtual DbSet<SZ_CartRFQ_Product> SZ_CartRFQ_Product { get; set; }
        public virtual DbSet<SZ_Category_Price> SZ_Category_Price { get; set; }
        public virtual DbSet<SZ_CategoryMaster> SZ_CategoryMaster { get; set; }
        public virtual DbSet<SZ_CategoryMasterRange> SZ_CategoryMasterRange { get; set; }
        public virtual DbSet<SZ_ChildCOA> SZ_ChildCOA { get; set; }
        public virtual DbSet<SZ_ClubQuote> SZ_ClubQuote { get; set; }
        public virtual DbSet<SZ_CompanyList> SZ_CompanyList { get; set; }
        public virtual DbSet<SZ_Courier> SZ_Courier { get; set; }
        public virtual DbSet<SZ_Currency> SZ_Currency { get; set; }
        public virtual DbSet<Sz_DatabaseBackup> Sz_DatabaseBackup { get; set; }
        public virtual DbSet<SZ_DeleteRetest> SZ_DeleteRetest { get; set; }
        public virtual DbSet<SZ_EmailSuggestion> SZ_EmailSuggestion { get; set; }
        public virtual DbSet<SZ_Inventory> SZ_Inventory { get; set; }
        public virtual DbSet<SZ_InventoryLog> SZ_InventoryLog { get; set; }
        public virtual DbSet<SZ_Invoice> SZ_Invoice { get; set; }
        public virtual DbSet<SZ_InvoiceData> SZ_InvoiceData { get; set; }
        public virtual DbSet<SZ_InvoiceDetailsData> SZ_InvoiceDetailsData { get; set; }
        public virtual DbSet<SZ_Log> SZ_Log { get; set; }
        public virtual DbSet<SZ_MasterCOA> SZ_MasterCOA { get; set; }
        public virtual DbSet<SZ_NameMaster> SZ_NameMaster { get; set; }
        public virtual DbSet<SZ_Notification> SZ_Notification { get; set; }
        public virtual DbSet<SZ_Physicalstate> SZ_Physicalstate { get; set; }
        public virtual DbSet<SZ_Price> SZ_Price { get; set; }
        public virtual DbSet<SZ_PriceList> SZ_PriceList { get; set; }
        public virtual DbSet<SZ_Project> SZ_Project { get; set; }
        public virtual DbSet<SZ_ProjectDetail> SZ_ProjectDetail { get; set; }
        public virtual DbSet<SZ_PurchaseRFQ> SZ_PurchaseRFQ { get; set; }
        public virtual DbSet<SZ_Query> SZ_Query { get; set; }
        public virtual DbSet<SZ_QueryModule> SZ_QueryModule { get; set; }
        public virtual DbSet<SZ_Quotation> SZ_Quotation { get; set; }
        public virtual DbSet<SZ_QuotationDetail> SZ_QuotationDetail { get; set; }
        public virtual DbSet<SZ_QuotationDetailLog> SZ_QuotationDetailLog { get; set; }
        public virtual DbSet<SZ_QuoteDetailForm> SZ_QuoteDetailForm { get; set; }
        public virtual DbSet<SZ_QuoteDetails_Form> SZ_QuoteDetails_Form { get; set; }
        public virtual DbSet<SZ_QuoteDetailsComment> SZ_QuoteDetailsComment { get; set; }
        public virtual DbSet<SZ_Retest> SZ_Retest { get; set; }
        public virtual DbSet<SZ_SampleRequest> SZ_SampleRequest { get; set; }
        public virtual DbSet<SZ_SampleRequestDetail> SZ_SampleRequestDetail { get; set; }
        public virtual DbSet<SZ_ScientistStatus> SZ_ScientistStatus { get; set; }
        public virtual DbSet<SZ_SolutionModule> SZ_SolutionModule { get; set; }
        public virtual DbSet<SZ_Survey> SZ_Survey { get; set; }
        public virtual DbSet<SZ_TempQuickAdd> SZ_TempQuickAdd { get; set; }
        public virtual DbSet<SZ_TempQuotationDetail> SZ_TempQuotationDetail { get; set; }
        public virtual DbSet<SZ_Terms> SZ_Terms { get; set; }
        public virtual DbSet<SZ_UserDashboard> SZ_UserDashboard { get; set; }
        public virtual DbSet<TaxCategory> TaxCategories { get; set; }
        public virtual DbSet<TaxRate> TaxRates { get; set; }
        public virtual DbSet<TierPrice> TierPrices { get; set; }
        public virtual DbSet<Topic> Topics { get; set; }
        public virtual DbSet<TopicTemplate> TopicTemplates { get; set; }
        public virtual DbSet<UrlRecord> UrlRecords { get; set; }
        public virtual DbSet<Vendor> Vendors { get; set; }
        public virtual DbSet<Warehouse> Warehouses { get; set; }
        public virtual DbSet<QuotationAndDetailsView> QuotationAndDetailsViews { get; set; }
        public virtual DbSet<QuoteandDetailsview> QuoteandDetailsviews { get; set; }
    
        [DbFunction("SynzealEntities", "nop_splitstring_to_table")]
        public virtual IQueryable<nop_splitstring_to_table_Result> nop_splitstring_to_table(string @string, string delimiter)
        {
            var stringParameter = @string != null ?
                new ObjectParameter("string", @string) :
                new ObjectParameter("string", typeof(string));
    
            var delimiterParameter = delimiter != null ?
                new ObjectParameter("delimiter", delimiter) :
                new ObjectParameter("delimiter", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<nop_splitstring_to_table_Result>("[SynzealEntities].[nop_splitstring_to_table](@string, @delimiter)", stringParameter, delimiterParameter);
        }
    
        public virtual int BackUpDatabase(string nameOfDatabase)
        {
            var nameOfDatabaseParameter = nameOfDatabase != null ?
                new ObjectParameter("nameOfDatabase", nameOfDatabase) :
                new ObjectParameter("nameOfDatabase", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BackUpDatabase", nameOfDatabaseParameter);
        }
    
        public virtual ObjectResult<CompanyList_Result> CompanyList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CompanyList_Result>("CompanyList");
        }
    
        public virtual int Dashboard()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Dashboard");
        }
    
        public virtual int DeleteGuests(Nullable<bool> onlyWithoutShoppingCart, Nullable<System.DateTime> createdFromUtc, Nullable<System.DateTime> createdToUtc, ObjectParameter totalRecordsDeleted)
        {
            var onlyWithoutShoppingCartParameter = onlyWithoutShoppingCart.HasValue ?
                new ObjectParameter("OnlyWithoutShoppingCart", onlyWithoutShoppingCart) :
                new ObjectParameter("OnlyWithoutShoppingCart", typeof(bool));
    
            var createdFromUtcParameter = createdFromUtc.HasValue ?
                new ObjectParameter("CreatedFromUtc", createdFromUtc) :
                new ObjectParameter("CreatedFromUtc", typeof(System.DateTime));
    
            var createdToUtcParameter = createdToUtc.HasValue ?
                new ObjectParameter("CreatedToUtc", createdToUtc) :
                new ObjectParameter("CreatedToUtc", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteGuests", onlyWithoutShoppingCartParameter, createdFromUtcParameter, createdToUtcParameter, totalRecordsDeleted);
        }
    
        public virtual int DispatchedDeliveredList(string searchString, Nullable<int> pageNumber, Nullable<int> pageSize)
        {
            var searchStringParameter = searchString != null ?
                new ObjectParameter("searchString", searchString) :
                new ObjectParameter("searchString", typeof(string));
    
            var pageNumberParameter = pageNumber.HasValue ?
                new ObjectParameter("PageNumber", pageNumber) :
                new ObjectParameter("PageNumber", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DispatchedDeliveredList", searchStringParameter, pageNumberParameter, pageSizeParameter);
        }
    
        public virtual ObjectResult<FollowupOverview_Result> FollowupOverview(string action)
        {
            var actionParameter = action != null ?
                new ObjectParameter("action", action) :
                new ObjectParameter("action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FollowupOverview_Result>("FollowupOverview", actionParameter);
        }
    
        public virtual int FullText_Disable()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("FullText_Disable");
        }
    
        public virtual int FullText_Enable()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("FullText_Enable");
        }
    
        public virtual ObjectResult<Nullable<int>> FullText_IsSupported()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("FullText_IsSupported");
        }
    
        public virtual ObjectResult<Nullable<int>> GetScientistId()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("GetScientistId");
        }
    
        public virtual ObjectResult<InventoryList_Result> InventoryList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<InventoryList_Result>("InventoryList");
        }
    
        public virtual int InvoiceList(string countryType, string searchString, Nullable<int> pageNumber, Nullable<int> pageSize)
        {
            var countryTypeParameter = countryType != null ?
                new ObjectParameter("countryType", countryType) :
                new ObjectParameter("countryType", typeof(string));
    
            var searchStringParameter = searchString != null ?
                new ObjectParameter("searchString", searchString) :
                new ObjectParameter("searchString", typeof(string));
    
            var pageNumberParameter = pageNumber.HasValue ?
                new ObjectParameter("PageNumber", pageNumber) :
                new ObjectParameter("PageNumber", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InvoiceList", countryTypeParameter, searchStringParameter, pageNumberParameter, pageSizeParameter);
        }
    
        public virtual int LanguagePackImport(Nullable<int> languageId, string xmlPackage)
        {
            var languageIdParameter = languageId.HasValue ?
                new ObjectParameter("LanguageId", languageId) :
                new ObjectParameter("LanguageId", typeof(int));
    
            var xmlPackageParameter = xmlPackage != null ?
                new ObjectParameter("XmlPackage", xmlPackage) :
                new ObjectParameter("XmlPackage", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("LanguagePackImport", languageIdParameter, xmlPackageParameter);
        }
    
        public virtual int ProductAllTab(string searchby, string searchbyvalue, Nullable<int> pageNumber, Nullable<int> pageSize)
        {
            var searchbyParameter = searchby != null ?
                new ObjectParameter("searchby", searchby) :
                new ObjectParameter("searchby", typeof(string));
    
            var searchbyvalueParameter = searchbyvalue != null ?
                new ObjectParameter("searchbyvalue", searchbyvalue) :
                new ObjectParameter("searchbyvalue", typeof(string));
    
            var pageNumberParameter = pageNumber.HasValue ?
                new ObjectParameter("PageNumber", pageNumber) :
                new ObjectParameter("PageNumber", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ProductAllTab", searchbyParameter, searchbyvalueParameter, pageNumberParameter, pageSizeParameter);
        }
    
        public virtual int ProductLoadAllPaged(string categoryIds, Nullable<int> manufacturerId, Nullable<int> storeId, Nullable<int> vendorId, Nullable<int> warehouseId, Nullable<int> productTypeId, Nullable<bool> visibleIndividuallyOnly, Nullable<int> productTagId, Nullable<bool> featuredProducts, Nullable<decimal> priceMin, Nullable<decimal> priceMax, string keywords, Nullable<bool> searchDescriptions, Nullable<bool> searchSku, Nullable<bool> searchProductTags, Nullable<bool> useFullTextSearch, Nullable<int> fullTextMode, string filteredSpecs, Nullable<int> languageId, Nullable<int> orderBy, string allowedCustomerRoleIds, Nullable<int> pageIndex, Nullable<int> pageSize, Nullable<bool> showHidden, Nullable<bool> overridePublished, Nullable<bool> loadFilterableSpecificationAttributeOptionIds, ObjectParameter filterableSpecificationAttributeOptionIds, ObjectParameter totalRecords)
        {
            var categoryIdsParameter = categoryIds != null ?
                new ObjectParameter("CategoryIds", categoryIds) :
                new ObjectParameter("CategoryIds", typeof(string));
    
            var manufacturerIdParameter = manufacturerId.HasValue ?
                new ObjectParameter("ManufacturerId", manufacturerId) :
                new ObjectParameter("ManufacturerId", typeof(int));
    
            var storeIdParameter = storeId.HasValue ?
                new ObjectParameter("StoreId", storeId) :
                new ObjectParameter("StoreId", typeof(int));
    
            var vendorIdParameter = vendorId.HasValue ?
                new ObjectParameter("VendorId", vendorId) :
                new ObjectParameter("VendorId", typeof(int));
    
            var warehouseIdParameter = warehouseId.HasValue ?
                new ObjectParameter("WarehouseId", warehouseId) :
                new ObjectParameter("WarehouseId", typeof(int));
    
            var productTypeIdParameter = productTypeId.HasValue ?
                new ObjectParameter("ProductTypeId", productTypeId) :
                new ObjectParameter("ProductTypeId", typeof(int));
    
            var visibleIndividuallyOnlyParameter = visibleIndividuallyOnly.HasValue ?
                new ObjectParameter("VisibleIndividuallyOnly", visibleIndividuallyOnly) :
                new ObjectParameter("VisibleIndividuallyOnly", typeof(bool));
    
            var productTagIdParameter = productTagId.HasValue ?
                new ObjectParameter("ProductTagId", productTagId) :
                new ObjectParameter("ProductTagId", typeof(int));
    
            var featuredProductsParameter = featuredProducts.HasValue ?
                new ObjectParameter("FeaturedProducts", featuredProducts) :
                new ObjectParameter("FeaturedProducts", typeof(bool));
    
            var priceMinParameter = priceMin.HasValue ?
                new ObjectParameter("PriceMin", priceMin) :
                new ObjectParameter("PriceMin", typeof(decimal));
    
            var priceMaxParameter = priceMax.HasValue ?
                new ObjectParameter("PriceMax", priceMax) :
                new ObjectParameter("PriceMax", typeof(decimal));
    
            var keywordsParameter = keywords != null ?
                new ObjectParameter("Keywords", keywords) :
                new ObjectParameter("Keywords", typeof(string));
    
            var searchDescriptionsParameter = searchDescriptions.HasValue ?
                new ObjectParameter("SearchDescriptions", searchDescriptions) :
                new ObjectParameter("SearchDescriptions", typeof(bool));
    
            var searchSkuParameter = searchSku.HasValue ?
                new ObjectParameter("SearchSku", searchSku) :
                new ObjectParameter("SearchSku", typeof(bool));
    
            var searchProductTagsParameter = searchProductTags.HasValue ?
                new ObjectParameter("SearchProductTags", searchProductTags) :
                new ObjectParameter("SearchProductTags", typeof(bool));
    
            var useFullTextSearchParameter = useFullTextSearch.HasValue ?
                new ObjectParameter("UseFullTextSearch", useFullTextSearch) :
                new ObjectParameter("UseFullTextSearch", typeof(bool));
    
            var fullTextModeParameter = fullTextMode.HasValue ?
                new ObjectParameter("FullTextMode", fullTextMode) :
                new ObjectParameter("FullTextMode", typeof(int));
    
            var filteredSpecsParameter = filteredSpecs != null ?
                new ObjectParameter("FilteredSpecs", filteredSpecs) :
                new ObjectParameter("FilteredSpecs", typeof(string));
    
            var languageIdParameter = languageId.HasValue ?
                new ObjectParameter("LanguageId", languageId) :
                new ObjectParameter("LanguageId", typeof(int));
    
            var orderByParameter = orderBy.HasValue ?
                new ObjectParameter("OrderBy", orderBy) :
                new ObjectParameter("OrderBy", typeof(int));
    
            var allowedCustomerRoleIdsParameter = allowedCustomerRoleIds != null ?
                new ObjectParameter("AllowedCustomerRoleIds", allowedCustomerRoleIds) :
                new ObjectParameter("AllowedCustomerRoleIds", typeof(string));
    
            var pageIndexParameter = pageIndex.HasValue ?
                new ObjectParameter("PageIndex", pageIndex) :
                new ObjectParameter("PageIndex", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            var showHiddenParameter = showHidden.HasValue ?
                new ObjectParameter("ShowHidden", showHidden) :
                new ObjectParameter("ShowHidden", typeof(bool));
    
            var overridePublishedParameter = overridePublished.HasValue ?
                new ObjectParameter("OverridePublished", overridePublished) :
                new ObjectParameter("OverridePublished", typeof(bool));
    
            var loadFilterableSpecificationAttributeOptionIdsParameter = loadFilterableSpecificationAttributeOptionIds.HasValue ?
                new ObjectParameter("LoadFilterableSpecificationAttributeOptionIds", loadFilterableSpecificationAttributeOptionIds) :
                new ObjectParameter("LoadFilterableSpecificationAttributeOptionIds", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ProductLoadAllPaged", categoryIdsParameter, manufacturerIdParameter, storeIdParameter, vendorIdParameter, warehouseIdParameter, productTypeIdParameter, visibleIndividuallyOnlyParameter, productTagIdParameter, featuredProductsParameter, priceMinParameter, priceMaxParameter, keywordsParameter, searchDescriptionsParameter, searchSkuParameter, searchProductTagsParameter, useFullTextSearchParameter, fullTextModeParameter, filteredSpecsParameter, languageIdParameter, orderByParameter, allowedCustomerRoleIdsParameter, pageIndexParameter, pageSizeParameter, showHiddenParameter, overridePublishedParameter, loadFilterableSpecificationAttributeOptionIdsParameter, filterableSpecificationAttributeOptionIds, totalRecords);
        }
    
        public virtual ObjectResult<ProductTagCountLoadAll_Result> ProductTagCountLoadAll(Nullable<int> storeId)
        {
            var storeIdParameter = storeId.HasValue ?
                new ObjectParameter("StoreId", storeId) :
                new ObjectParameter("StoreId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProductTagCountLoadAll_Result>("ProductTagCountLoadAll", storeIdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Project_Count()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Project_Count");
        }
    
        public virtual ObjectResult<Project_HoldTab_Result> Project_HoldTab()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Project_HoldTab_Result>("Project_HoldTab");
        }
    
        public virtual int QuotationList(string searchString, string company, string date, string countrytype, string tabName, string searchby, string searchbyvalue, Nullable<int> pageNumber, Nullable<int> pageSize)
        {
            var searchStringParameter = searchString != null ?
                new ObjectParameter("searchString", searchString) :
                new ObjectParameter("searchString", typeof(string));
    
            var companyParameter = company != null ?
                new ObjectParameter("company", company) :
                new ObjectParameter("company", typeof(string));
    
            var dateParameter = date != null ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(string));
    
            var countrytypeParameter = countrytype != null ?
                new ObjectParameter("countrytype", countrytype) :
                new ObjectParameter("countrytype", typeof(string));
    
            var tabNameParameter = tabName != null ?
                new ObjectParameter("tabName", tabName) :
                new ObjectParameter("tabName", typeof(string));
    
            var searchbyParameter = searchby != null ?
                new ObjectParameter("searchby", searchby) :
                new ObjectParameter("searchby", typeof(string));
    
            var searchbyvalueParameter = searchbyvalue != null ?
                new ObjectParameter("searchbyvalue", searchbyvalue) :
                new ObjectParameter("searchbyvalue", typeof(string));
    
            var pageNumberParameter = pageNumber.HasValue ?
                new ObjectParameter("PageNumber", pageNumber) :
                new ObjectParameter("PageNumber", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("QuotationList", searchStringParameter, companyParameter, dateParameter, countrytypeParameter, tabNameParameter, searchbyParameter, searchbyvalueParameter, pageNumberParameter, pageSizeParameter);
        }
    
        public virtual int QuotationList_Backup(string searchString, string company, string date, string countrytype, string tabName, string searchby, string searchbyvalue, Nullable<int> pageNumber, Nullable<int> pageSize)
        {
            var searchStringParameter = searchString != null ?
                new ObjectParameter("searchString", searchString) :
                new ObjectParameter("searchString", typeof(string));
    
            var companyParameter = company != null ?
                new ObjectParameter("company", company) :
                new ObjectParameter("company", typeof(string));
    
            var dateParameter = date != null ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(string));
    
            var countrytypeParameter = countrytype != null ?
                new ObjectParameter("countrytype", countrytype) :
                new ObjectParameter("countrytype", typeof(string));
    
            var tabNameParameter = tabName != null ?
                new ObjectParameter("tabName", tabName) :
                new ObjectParameter("tabName", typeof(string));
    
            var searchbyParameter = searchby != null ?
                new ObjectParameter("searchby", searchby) :
                new ObjectParameter("searchby", typeof(string));
    
            var searchbyvalueParameter = searchbyvalue != null ?
                new ObjectParameter("searchbyvalue", searchbyvalue) :
                new ObjectParameter("searchbyvalue", typeof(string));
    
            var pageNumberParameter = pageNumber.HasValue ?
                new ObjectParameter("PageNumber", pageNumber) :
                new ObjectParameter("PageNumber", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("QuotationList_Backup", searchStringParameter, companyParameter, dateParameter, countrytypeParameter, tabNameParameter, searchbyParameter, searchbyvalueParameter, pageNumberParameter, pageSizeParameter);
        }
    
        public virtual ObjectResult<sp_BlitzCache_Result> sp_BlitzCache(Nullable<bool> help, Nullable<int> top, string sortOrder, Nullable<bool> useTriggersAnyway, Nullable<bool> exportToExcel, Nullable<byte> expertMode, string outputServerName, string outputDatabaseName, string outputSchemaName, string outputTableName, string configurationDatabaseName, string configurationSchemaName, string configurationTableName, Nullable<decimal> durationFilter, Nullable<bool> hideSummary, Nullable<bool> ignoreSystemDBs, string onlyQueryHashes, string ignoreQueryHashes, string onlySqlHandles, string ignoreSqlHandles, string queryFilter, string databaseName, string storedProcName, string slowlySearchPlansFor, Nullable<bool> reanalyze, Nullable<bool> skipAnalysis, Nullable<bool> bringThePain, Nullable<int> minimumExecutionCount, Nullable<bool> debug, Nullable<System.DateTimeOffset> checkDateOverride, Nullable<int> minutesBack, ObjectParameter version, ObjectParameter versionDate, Nullable<bool> versionCheckMode)
        {
            var helpParameter = help.HasValue ?
                new ObjectParameter("Help", help) :
                new ObjectParameter("Help", typeof(bool));
    
            var topParameter = top.HasValue ?
                new ObjectParameter("Top", top) :
                new ObjectParameter("Top", typeof(int));
    
            var sortOrderParameter = sortOrder != null ?
                new ObjectParameter("SortOrder", sortOrder) :
                new ObjectParameter("SortOrder", typeof(string));
    
            var useTriggersAnywayParameter = useTriggersAnyway.HasValue ?
                new ObjectParameter("UseTriggersAnyway", useTriggersAnyway) :
                new ObjectParameter("UseTriggersAnyway", typeof(bool));
    
            var exportToExcelParameter = exportToExcel.HasValue ?
                new ObjectParameter("ExportToExcel", exportToExcel) :
                new ObjectParameter("ExportToExcel", typeof(bool));
    
            var expertModeParameter = expertMode.HasValue ?
                new ObjectParameter("ExpertMode", expertMode) :
                new ObjectParameter("ExpertMode", typeof(byte));
    
            var outputServerNameParameter = outputServerName != null ?
                new ObjectParameter("OutputServerName", outputServerName) :
                new ObjectParameter("OutputServerName", typeof(string));
    
            var outputDatabaseNameParameter = outputDatabaseName != null ?
                new ObjectParameter("OutputDatabaseName", outputDatabaseName) :
                new ObjectParameter("OutputDatabaseName", typeof(string));
    
            var outputSchemaNameParameter = outputSchemaName != null ?
                new ObjectParameter("OutputSchemaName", outputSchemaName) :
                new ObjectParameter("OutputSchemaName", typeof(string));
    
            var outputTableNameParameter = outputTableName != null ?
                new ObjectParameter("OutputTableName", outputTableName) :
                new ObjectParameter("OutputTableName", typeof(string));
    
            var configurationDatabaseNameParameter = configurationDatabaseName != null ?
                new ObjectParameter("ConfigurationDatabaseName", configurationDatabaseName) :
                new ObjectParameter("ConfigurationDatabaseName", typeof(string));
    
            var configurationSchemaNameParameter = configurationSchemaName != null ?
                new ObjectParameter("ConfigurationSchemaName", configurationSchemaName) :
                new ObjectParameter("ConfigurationSchemaName", typeof(string));
    
            var configurationTableNameParameter = configurationTableName != null ?
                new ObjectParameter("ConfigurationTableName", configurationTableName) :
                new ObjectParameter("ConfigurationTableName", typeof(string));
    
            var durationFilterParameter = durationFilter.HasValue ?
                new ObjectParameter("DurationFilter", durationFilter) :
                new ObjectParameter("DurationFilter", typeof(decimal));
    
            var hideSummaryParameter = hideSummary.HasValue ?
                new ObjectParameter("HideSummary", hideSummary) :
                new ObjectParameter("HideSummary", typeof(bool));
    
            var ignoreSystemDBsParameter = ignoreSystemDBs.HasValue ?
                new ObjectParameter("IgnoreSystemDBs", ignoreSystemDBs) :
                new ObjectParameter("IgnoreSystemDBs", typeof(bool));
    
            var onlyQueryHashesParameter = onlyQueryHashes != null ?
                new ObjectParameter("OnlyQueryHashes", onlyQueryHashes) :
                new ObjectParameter("OnlyQueryHashes", typeof(string));
    
            var ignoreQueryHashesParameter = ignoreQueryHashes != null ?
                new ObjectParameter("IgnoreQueryHashes", ignoreQueryHashes) :
                new ObjectParameter("IgnoreQueryHashes", typeof(string));
    
            var onlySqlHandlesParameter = onlySqlHandles != null ?
                new ObjectParameter("OnlySqlHandles", onlySqlHandles) :
                new ObjectParameter("OnlySqlHandles", typeof(string));
    
            var ignoreSqlHandlesParameter = ignoreSqlHandles != null ?
                new ObjectParameter("IgnoreSqlHandles", ignoreSqlHandles) :
                new ObjectParameter("IgnoreSqlHandles", typeof(string));
    
            var queryFilterParameter = queryFilter != null ?
                new ObjectParameter("QueryFilter", queryFilter) :
                new ObjectParameter("QueryFilter", typeof(string));
    
            var databaseNameParameter = databaseName != null ?
                new ObjectParameter("DatabaseName", databaseName) :
                new ObjectParameter("DatabaseName", typeof(string));
    
            var storedProcNameParameter = storedProcName != null ?
                new ObjectParameter("StoredProcName", storedProcName) :
                new ObjectParameter("StoredProcName", typeof(string));
    
            var slowlySearchPlansForParameter = slowlySearchPlansFor != null ?
                new ObjectParameter("SlowlySearchPlansFor", slowlySearchPlansFor) :
                new ObjectParameter("SlowlySearchPlansFor", typeof(string));
    
            var reanalyzeParameter = reanalyze.HasValue ?
                new ObjectParameter("Reanalyze", reanalyze) :
                new ObjectParameter("Reanalyze", typeof(bool));
    
            var skipAnalysisParameter = skipAnalysis.HasValue ?
                new ObjectParameter("SkipAnalysis", skipAnalysis) :
                new ObjectParameter("SkipAnalysis", typeof(bool));
    
            var bringThePainParameter = bringThePain.HasValue ?
                new ObjectParameter("BringThePain", bringThePain) :
                new ObjectParameter("BringThePain", typeof(bool));
    
            var minimumExecutionCountParameter = minimumExecutionCount.HasValue ?
                new ObjectParameter("MinimumExecutionCount", minimumExecutionCount) :
                new ObjectParameter("MinimumExecutionCount", typeof(int));
    
            var debugParameter = debug.HasValue ?
                new ObjectParameter("Debug", debug) :
                new ObjectParameter("Debug", typeof(bool));
    
            var checkDateOverrideParameter = checkDateOverride.HasValue ?
                new ObjectParameter("CheckDateOverride", checkDateOverride) :
                new ObjectParameter("CheckDateOverride", typeof(System.DateTimeOffset));
    
            var minutesBackParameter = minutesBack.HasValue ?
                new ObjectParameter("MinutesBack", minutesBack) :
                new ObjectParameter("MinutesBack", typeof(int));
    
            var versionCheckModeParameter = versionCheckMode.HasValue ?
                new ObjectParameter("VersionCheckMode", versionCheckMode) :
                new ObjectParameter("VersionCheckMode", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_BlitzCache_Result>("sp_BlitzCache", helpParameter, topParameter, sortOrderParameter, useTriggersAnywayParameter, exportToExcelParameter, expertModeParameter, outputServerNameParameter, outputDatabaseNameParameter, outputSchemaNameParameter, outputTableNameParameter, configurationDatabaseNameParameter, configurationSchemaNameParameter, configurationTableNameParameter, durationFilterParameter, hideSummaryParameter, ignoreSystemDBsParameter, onlyQueryHashesParameter, ignoreQueryHashesParameter, onlySqlHandlesParameter, ignoreSqlHandlesParameter, queryFilterParameter, databaseNameParameter, storedProcNameParameter, slowlySearchPlansForParameter, reanalyzeParameter, skipAnalysisParameter, bringThePainParameter, minimumExecutionCountParameter, debugParameter, checkDateOverrideParameter, minutesBackParameter, version, versionDate, versionCheckModeParameter);
        }
    
        public virtual int SynthesisLog(string searchString, Nullable<int> pageNumber, Nullable<int> pageSize)
        {
            var searchStringParameter = searchString != null ?
                new ObjectParameter("searchString", searchString) :
                new ObjectParameter("searchString", typeof(string));
    
            var pageNumberParameter = pageNumber.HasValue ?
                new ObjectParameter("PageNumber", pageNumber) :
                new ObjectParameter("PageNumber", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SynthesisLog", searchStringParameter, pageNumberParameter, pageSizeParameter);
        }
    }
}
