//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Synzeal_BatchFormData_Sync.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SZ_CategoryMaster
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Ten { get; set; }
        public Nullable<int> Twentyfive { get; set; }
        public Nullable<int> Fifty { get; set; }
        public Nullable<int> Onehundred { get; set; }
        public Nullable<int> TwohundredFifty { get; set; }
        public Nullable<int> Fivehundred { get; set; }
        public Nullable<int> OneThousand { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Updateddate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<int> TenUSD { get; set; }
        public Nullable<int> TwentyfiveUSD { get; set; }
        public Nullable<int> FiftyUSD { get; set; }
        public Nullable<int> OnehundredUSD { get; set; }
        public Nullable<int> TwohundredFiftyUSD { get; set; }
        public Nullable<int> FivehundredUSD { get; set; }
        public Nullable<int> OneThousandUSD { get; set; }
        public Nullable<int> Rating { get; set; }
    }
}
